name = "bentolink-bio-website-tuliopinheirocunha"
main = "dist/_worker.js"
compatibility_date = "2024-10-25"
compatibility_flags = ["nodejs_compat"]

[build]
command = "bun run build"

[assets]
directory = "dist"
