name = "bentolink-bio-website-tuliopinheirocunha"
main = "dist/_worker.js"
compatibility_date = "2024-10-25"
compatibility_flags = ["nodejs_compat"]

[build]
command = "bun run build"

[assets]
directory = "dist"

[vars]
PUBLIC_GITHUB_USERNAME = "tuliopc23"
PUBLIC_SANITY_PROJECT_ID = "61249gtj"
PUBLIC_SANITY_DATASET = "production"
PUBLIC_SANITY_API_VERSION = "2023-05-03"
